kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31000
        hostPort: 80
        protocol: TCP
      - containerPort: 31443
        hostPort: 443
        protocol: TCP
      - containerPort: 32001
        hostPort: 32001
        protocol: TCP
      - containerPort: 32000
        hostPort: 32000
        protocol: TCP
  - role: worker
